id = "jannchie-code"
name = "Jannchie Code"
version = "3.1.1"
schema_version = 1
authors = [ "Jannchie <jannchie@gmail.com>" ]
description = "Jannchie Code Theme for Zed"
repository = "https://github.com/jannchie/vscode-theme"
