import type { ThemeColorGroups, ThemeVariant } from './colorTypes'
import { applyOpacity, colorTokens } from './colorTokens'

const lightThemeColors = {
  text: {
    primary: colorTokens.light.base.textPrimary,
    active: colorTokens.light.base.textActive,
    secondary: applyOpacity(colorTokens.light.base.textPrimary, 'high'),
    muted: applyOpacity(colorTokens.light.base.textPrimary, 'lower'),
    subtle: applyOpacity(colorTokens.light.base.textPrimary, 'faint'),
  },
  surface: {
    canvas: colorTokens.light.surface.canvas,
    panel: colorTokens.light.base.panel,
    border: colorTokens.light.surface.border,
    overlay: colorTokens.light.base.textPrimary,
    guide: colorTokens.light.base.textPrimary,
    shadow: colorTokens.light.surface.shadow,
  },
  syntax: {
    comment: colorTokens.light.syntax.comment,
    string: colorTokens.light.syntax.string,
    readonly: colorTokens.light.syntax.readonly,
    variable: colorTokens.light.base.textActive,
    parameter: colorTokens.light.syntax.parameter,
    variableBuiltin: colorTokens.light.syntax.variableBuiltin,
    property: colorTokens.light.syntax.property,
    keyword: colorTokens.light.accent.blue,
    number: colorTokens.light.syntax.number,
    boolean: colorTokens.light.syntax.boolean,
    constant: colorTokens.light.syntax.constant,
    namespace: colorTokens.light.syntax.namespace,
    operator: colorTokens.light.syntax.namespace,
    builtin: colorTokens.light.syntax.namespace,
    function: colorTokens.light.syntax.function,
    functionBuiltin: colorTokens.light.syntax.function,
    class: colorTokens.light.syntax.class,
    classBuiltin: colorTokens.light.syntax.classBuiltin,
    type: colorTokens.light.syntax.type,
    interface: colorTokens.light.syntax.interface,
    punctuation: colorTokens.light.syntax.punctuation,
    decorator: colorTokens.light.syntax.decorator,
    regex: colorTokens.light.syntax.regex,
  },
  accent: {
    primary: colorTokens.light.accent.primary,
    blue: colorTokens.light.accent.blue,
    cyan: colorTokens.light.accent.cyan,
    green: colorTokens.light.accent.green,
    magenta: colorTokens.light.accent.magenta,
    orange: colorTokens.light.accent.orange,
    red: colorTokens.light.accent.red,
    yellow: colorTokens.light.accent.yellow,
  },
  utility: {
    transparent: colorTokens.shared.transparent,
    terminalBlack: colorTokens.light.utility.terminalBlack,
    peekMatchBackground: colorTokens.light.utility.peekMatchBackground,
  },
} satisfies ThemeColorGroups

const darkThemeColors = {
  text: {
    primary: colorTokens.dark.base.textPrimary,
    active: colorTokens.dark.base.textActive,
    secondary: applyOpacity(colorTokens.dark.base.textActive, 'medium'),
    muted: applyOpacity(colorTokens.dark.base.textActive, 'low'),
    subtle: applyOpacity(colorTokens.dark.base.textActive, 'faint'),
  },
  surface: {
    canvas: colorTokens.dark.surface.canvas,
    panel: colorTokens.dark.base.panel,
    border: colorTokens.dark.surface.border,
    overlay: colorTokens.dark.surface.overlay,
    guide: colorTokens.dark.surface.guide,
    shadow: colorTokens.dark.surface.shadow,
  },
  syntax: {
    comment: colorTokens.dark.syntax.comment,
    string: colorTokens.dark.syntax.string,
    readonly: colorTokens.dark.syntax.readonly,
    variable: colorTokens.dark.syntax.variable,
    parameter: colorTokens.dark.syntax.variable,
    variableBuiltin: colorTokens.dark.syntax.variable,
    property: colorTokens.dark.syntax.variable,
    keyword: colorTokens.dark.accent.blue,
    number: colorTokens.dark.syntax.number,
    boolean: colorTokens.dark.syntax.boolean,
    constant: colorTokens.dark.syntax.constant,
    namespace: colorTokens.dark.syntax.namespace,
    operator: colorTokens.dark.syntax.namespace,
    builtin: colorTokens.dark.syntax.namespace,
    function: colorTokens.dark.syntax.function,
    functionBuiltin: colorTokens.dark.syntax.functionBuiltin,
    class: colorTokens.dark.syntax.class,
    classBuiltin: colorTokens.dark.syntax.classBuiltin,
    type: colorTokens.dark.syntax.class,
    interface: colorTokens.dark.syntax.class,
    punctuation: colorTokens.dark.syntax.punctuation,
    decorator: colorTokens.dark.syntax.decorator,
    regex: colorTokens.dark.syntax.regex,
  },
  accent: {
    primary: colorTokens.dark.accent.primary,
    blue: colorTokens.dark.accent.blue,
    cyan: colorTokens.dark.accent.cyan,
    green: colorTokens.dark.accent.green,
    magenta: colorTokens.dark.accent.magenta,
    orange: colorTokens.dark.accent.orange,
    red: colorTokens.dark.accent.red,
    yellow: colorTokens.dark.accent.yellow,
  },
  utility: {
    transparent: colorTokens.shared.transparent,
    terminalBlack: colorTokens.dark.utility.terminalBlack,
    peekMatchBackground: colorTokens.dark.utility.peekMatchBackground,
  },
} satisfies ThemeColorGroups

export const baseThemeColors = {
  dark: darkThemeColors,
  light: lightThemeColors,
} as const satisfies Record<ThemeVariant, ThemeColorGroups>
